Ac fixed tutorial
wangdi4/oneAPI-samples pull request #1
Opened 2022-03-22 18:56 UTC by wangdi4

# Existing Sample Changes
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes Issue# 

## External Dependencies

List any external dependencies created as a result of this change.

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

**_Delete this line and everything below if this is not a PR for a new code sample_**

**_Delete this line and all above it if this PR is for a new code sample_**
# Adding a New Sample(s)

## Description

Please include a description of the sample

## Checklist
Administrative
- [ ] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager

Code Development
- [ ] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [ ] Adhere to readme template 
- [ ] Enforce format via clang-format config file
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see Project Manager for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [ ] Tested using Dev Cloud when applicable

2022-03-23 18:36 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +| What you will learn               | How different methods of `ac_fixed` number construction affect hardware resource utilization <br> Recommended method for constructing `ac_fixed` numbers in your
trade off  /  trade-off  /  tradeoff
trading off  /  trading-off

2022-03-23 18:49 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +The type also provides two more optional parameters for controlling the overflow and rounding modes. For more details on the type, please refer to the section titled `Variable-Precision Integer and F
Intel oneAPI ... Guide hyperlink?

2022-03-23 18:55 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +In contrast, the kernel `ConstructFromACFixed` constructs an `ac_fixed` object from an accessor to another `ac_fixed` object. This consumes far less area than the previous kernel. See the section on
"Examining the Report"

2022-03-23 19:06 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +The flag `-qactypes` on Linux or `/Qactypes` on Windows  will ensure that the compiler includes the header and links against the necessary libraries for emulation of the math library functions.
Additionally, you must pass the flag `-qactypes` on Linux or `/Qactypes` on Windows to the `dpcpp` command when compiling your SYCL program ~~in order to ensure that the headers are correctly included~~. In this tutorial, this is done in `src/CMakeLists.txt`.
=>
...for emulation of the math library functions...

2022-03-23 19:14 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +This tutorial design contains two kernels `CalculateWithFloat` and `CalculateWithACFixed`. Both calculate the simple expression:
contains two kernels that use the `ac_fixed` math functions: `CalculateWithFloat` and `CalculateWithACFixed`. ...

2022-03-23 19:14 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +To use this type in your code, you must include the following header:
To use `ac_fixed` math functions, ...

2022-03-23 19:22 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +Clearly, the `ac_fixed` numbers are smaller in size than floating point numbers. This results in reduction of the FPGA resources utilized by the functions at the expense of accuracy. To see the trade
```suggestion
Clearly, the `ac_fixed` numbers are smaller in size than floating point numbers. This results in reduction of the FPGA resources utilized by the functions at the expense of accuracy. To see the trade-offs between accuracy, compare the numeric results of the operations. The area utilization differences will be discussed in the section on `Examining the reports`.
```

2022-03-23 20:18 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +
Copy `Using Visual Studio Code*  (Optional)` section from ac_int tutorial

2022-03-24 15:17 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +PASSED
PASSED: ...

2022-03-25 13:46 UTC, tyoungsc requested changes

2022-03-25 13:46 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +This tutorial shows the recommended method for constructing an `ac_fixed` number, some examples of using the fixed point math library functions and how they can be used to reduce the area of the hard
```suggestion
This tutorial shows the recommended method for constructing an `ac_fixed` number, some examples of using the fixed point math library functions, and how they can be used to reduce the area of the hardware generated by the compiler by trading off accuracy of the mathematical operations.
```

2022-03-25 13:46 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +Here `W` specifies the width and `S` specifies the sign of the number. One of the `W` bits is used to store the sign information. The second parameter `I` is an integer that specifies the location of
Maybe a little ASCII art with an example? Like:
```For example, ac_int<10, 4, true> would give you the following <insert a little ASCII art about the bits and their positions".
```

Also, does S = true add a bit? Or is the decimal point 'I' positions from the sign bit / the MSB? Again, I think a few examples with ASCII art may help here.

2022-03-25 13:46 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +The type also provides two more optional parameters for controlling the overflow and rounding modes. For more details on the type, please refer to the section *Variable-Precision Integer and Floating
```suggestion
The `ac_fixed` class also provides two more optional parameters for controlling the overflow and rounding modes. For more details on the `ac_int` class, refer to the section *Variable-Precision Integer and Floating-Point Support* in the Intel® oneAPI DPC++ FPGA Optimization Guide.
```

2022-03-25 13:46 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +### Recommended Method for Constructing `ac_fixed` Numbers
Do we have the same gotchas here that we must initialize the ac_fixed to 0 if we want to manipulate individual bits? If so, it may be worth mentioning. (https://hsdes.intel.com/appstore/article/#/14015829976)

2022-03-25 13:46 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +Clearly, the `ac_fixed` numbers are smaller in size than floating point numbers. This results in reduction of the FPGA resources utilized by the functions at the expense of accuracy. To see the trade
```suggestion
The `ac_fixed` numbers are smaller in size than floating point numbers, which results in a reduction of the FPGA resources at the expense of accuracy. To see the trade-offs between accuracy compare the numeric results of the operations. The area utilization differences will be discussed in the section on *Examining the Reports*.
```

Additionally, I don't like this part "To see the trade-offs between accuracy compare the numeric results of the operations". Do we do that for the user? We should show the accuracy differences in the tutorial.

2022-03-25 13:46 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +    The host program (`main()` function) for this tutorial gives you an estimate of the difference between the correct result and the result provided by the math library functions. The floating point
```suggestion
    The host program for this tutorial shows the accuracy differences between the correct result and the result provided by the math library functions. The floating point version generates a more accurate result than the fixed point version.
```

1) Nevermind my earlier comment about showing this :)
2) What is the "correct" result? Do you list out EVERY decimal?

2022-03-25 13:46 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +    Due to the differences in the internal math implementations, the results from `ac_fixed` math functions in simulation and emulation might not always be bit-accurate. In this example you can obser
I am not sure we can claim support for simulation yet. Do these differences show up between emulation and hardware too? If so, show that instead.

2022-03-25 13:46 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> + - Emulation vs Simulation for fixed point math operations
Can we say emulation vs hardware here? Simulation support for these designs is not ready yet.

2022-03-25 13:46 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/sample.json
> +  "guid": "FB4643A1-64B1-4B09-9B98-4E23BA6D0925",
Did you generate a new one of these for this tutorial?

2022-03-25 13:46 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +    Due to the differences in the internal math implementations, the results from `ac_fixed` math functions in simulation and emulation might not always be bit-accurate. In this example you can obser
In fact, your cmake file doesn't have a simulation target, so certainly change this.

2022-03-25 13:46 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/src/ac_fixed.cpp
> +// reports.
```suggestion
// This is a FPGA best practice that reduces name mangling in the reports.
```

2022-03-25 13:46 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/src/ac_fixed.cpp
> +constexpr int SIZE = 5;
```suggestion
constexpr int kSize= 5;
```

And change all uses

2022-03-25 13:46 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/src/ac_fixed.cpp
> +                                    1.14324158042f};
Where are these numbers coming from? Anything in particular? Or just hand picked randoms?

2022-03-25 13:46 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/src/ac_fixed.cpp
> +    ac_fixed<20, 10, true, AC_RND, AC_SAT> b = 3.1415f;
Add a comment about what `AC_RND` and `AC_SAT` are, and where to find them.

2022-03-28 16:54 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/src/ac_fixed.cpp
> +    for (int i = 0; i < SIZE; i++) {
```suggestion
    for (int i = 0; i < kSize; i++) {
```

2022-03-28 16:55 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/src/ac_fixed.cpp
> +    constexpr float inputs[SIZE] = {-0.807991899423f, -2.09982907558f,
```suggestion
    constexpr float inputs[kSize] = {-0.807991899423f, -2.09982907558f,
```

2022-03-28 17:40 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/sample.json
> +  "guid": "FB4643A1-64B1-4B09-9B98-4E23BA6D0925",
Yes

2022-03-28 19:00 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +Here `W` specifies the width and `S` specifies the sign of the number. One of the `W` bits is used to store the sign information. The second parameter `I` is an integer that specifies the location of
Mention that the sign bit is the MSB of the W bits, and direct users to `ac_datatypes_ref.pdf` for more details.

2022-03-28 21:03 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/src/ac_fixed.cpp
> +                                    1.14324158042f};
These are inherited from the corresponding design in HLS tutorial.

2022-03-29 19:53 UTC, paul-white-intel requested changes
good tutorial, some small changes in the readme and source code.

please clarify some assumptions about why values of `W` and `I` were chosen.

please make code style for kernels more consistent.

2022-03-29 19:53 UTC, paul-white-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +    For fixed-point functions, each function has a default return type. Assigning the result to a non-default return type triggers a type conversion and can cause an increase in logic use or a loss o
you can also use the `auto` type to let the compiler use the default return type. 
bonus: mousing over the `auto` type in VS Code with C++ extension will show you what the type will evaluate to.

2022-03-29 19:53 UTC, paul-white-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/src/ac_fixed.cpp
> +      res[0] = sqrt_fixed(sin_ret * sin_ret + cos_ret * cos_ret);
We should clearly describe here (or in the readme) that the expression `sin_ret * sin_ret + cos_ret * cos_ret` will evaluate to a larger `ac_fixed`, and so the `W` and `I` parameters of the `sqrt_fixed` function will be larger than 9 and 2. The result gets truncated to fit in `res[0]`. Please verify in the report.

2022-03-30 21:13 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/src/ac_fixed.cpp
> +  buffer<ac_fixed<20, 10, true, AC_RND, AC_SAT>, 1> ret_val(&b, 1);
Using buffers and accessors we can continue targeting the PAC FPGA boards for compiles. With USM we would have to target boards that support USM. We can make this as an incremental update in the future.

2022-03-30 21:41 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/src/ac_fixed.cpp
> +  buffer<ac_fixed<20, 10, true, AC_RND, AC_SAT>, 1> ret_val(&b, 1);
Untrue. USM device allocations don't require the "USM" BSP (pac_s10_usm).
malloc_device (USM device allocations) are supported on all of our BSPs.
However, for now, keep it to buffers and accessors.
@paul-white-intel, we can do bulk changes later.

2022-03-31 19:47 UTC, wangdi4 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +    For fixed-point functions, each function has a default return type. Assigning the result to a non-default return type triggers a type conversion and can cause an increase in logic use or a loss o
Is it a better convention to declare the `ac_fixed` type explicitly, so users would be aware if loss of accuracy happens?

2022-04-06 17:58 UTC, paul-white-intel approved these changes
couple of minor changes. Great tutorial!

2022-04-06 17:58 UTC, paul-white-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +For more details on the `ac_fixed` class, please refer to the documentation provided with the installation at `<installation path>/lib/oclfpga/include/ref/ac_datatypes_ref.pdf`.
sorry to change this again, here is an external link that points to the correct version of the doc: https://github.com/hlslibs/ac_types/blob/v3.7/pdfdocs/ac_datatypes_ref.pdf

2022-04-08 15:53 UTC, tiwaria1 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +For more details on the `ac_fixed` class, please refer to the documentation provided with the installation at `<installation path>/lib/oclfpga/include/ref/ac_datatypes_ref.pdf`.
Hi @paul-white-intel , is there a concern about the new updated path we have put here? I don't think we want to point to an external doc URL which may change without notice.

2022-04-08 16:04 UTC, tiwaria1 commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +#include <sycl/ext/intel/ac_types/ac_fixed.hpp>
`./compiler/2022.0.2/linux/include/sycl/CL/sycl/INTEL/ac_types/ac_fixed.hpp`
and
`./compiler/2022.0.2/linux/lib/oclfpga/include/CL/sycl/INTEL/ac_types/ac_fixed.hpp`
- We keep this for backwards compatibility. We don't need two of these. I will follow up with others to figure why there are two of these.

`./compiler/2022.0.2/linux/lib/oclfpga/include/sycl/ext/intel/ac_types/ac_fixed.hpp` - This is the current location.

2022-04-08 17:45 UTC, wangdi4 commented
Move to the main repo.

2022-04-11 15:05 UTC, paul-white-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +For more details on the `ac_fixed` class, please refer to the documentation provided with the installation at `<installation path>/lib/oclfpga/include/ref/ac_datatypes_ref.pdf`.
we will eventually host our own copy of the ac_int docs; Eric and VJ are supposed to be working on that (we got endorsement from steering committee last week). My thought was that we would point to the github link until we have an intel.com/.../ac_datatypes_ref.pdf link available; but if you would like to avoid thrashing on the code samples we can link to the [oneAPI FPGA optimization guide](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-fpga-optimization-guide/top/optimize-your-design/resource-use/data-types-and-operations/var-prec-fp-sup.html), and link to the Siemens doc from our optimization guide.

2022-04-19 19:28 UTC, erickoeck commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +For more details on the `ac_fixed` class, please refer to the documentation provided with the installation at `<installation path>/lib/oclfpga/include/ref/ac_datatypes_ref.pdf`.
Intel-hosted version is now available at https://cdrdv2.intel.com/v1/dl/getContent/728986

2022-06-12 21:43 UTC, closed without merging