Add utility function for annotated malloc
wangdi4/oneAPI-samples pull request #12
Opened 2023-12-14 15:18 UTC by wangdi4

# Existing Sample Changes
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes Issue# 

## External Dependencies

List any external dependencies created as a result of this change.

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

2023-12-14 22:20 UTC, ajaykumarkannan approved these changes

2023-12-18 15:46 UTC, yuguen-intel reviewed
Let's have a chat so that you can explain to me what this is doing, and how it helps the user
Thanks!

2023-12-18 15:46 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/include/annotated_class_util.hpp
> +#include <sycl/sycl.hpp>
For this file to be included in the various plugins for the code samples (VS, eclipse, etc.), you'll need to modify the `sample.json` files for the code samples that uses it.

2023-12-18 15:46 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/include/annotated_class_util.hpp
> +using namespace sycl::ext::oneapi::experimental;
Can you be explicit in the code rather than using `using namespace`?

2023-12-18 22:53 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/component_interfaces_comparison/mm-host/src/vector_add.cpp
> +    auto c = fpga_tools::alloc_annotated<karg_c_t>(count, q);
does the `auto` evaluate to an explicit type in an IDE like VS Code? If not then you should explicitly specify the type here to make a user's life easy.

2023-12-18 22:53 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/component_interfaces_comparison/mm-host/src/vector_add.cpp
>    sycl::ext::oneapi::experimental::annotated_arg<
why not create a type alias for `a_in` and `b_in`?

2023-12-18 22:53 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/component_interfaces_comparison/mm-host/src/vector_add.cpp
> +using karg_c_t = sycl::ext::oneapi::experimental::annotated_arg<
why is the name `karg_c_t`? I don't understand what that is shorthand for. `k` as a prefix usually means a `constexpr`, i'd suggest something like `c_out_t` or something.

2023-12-18 22:53 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost/part3_hosts/src/mmhost.cpp
> +  karg_z_t z;
this shorthand should be applied to all kernel arguments.

2023-12-19 08:38 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/include/annotated_class_util.hpp
> +// malloc_shared" in allocating host/share memory in the following aspects:
```suggestion
// "malloc_shared" in allocating host/share memory in the following aspects:
```

2023-12-19 17:00 UTC, whitepau requested changes

2023-12-19 17:00 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/include/annotated_class_util.hpp
> +// can be symplified as:
```suggestion
// can be simplified as:
```

2023-12-19 17:00 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/include/annotated_class_util.hpp
> +// parameter, and returns an instance of that annotated_arg type. This provides
```suggestion
// parameter, and returns an instance of that annotated_arg's template type. This provides
```

2023-12-19 17:00 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/include/annotated_class_util.hpp
> +// compile-time guarantee that the properties of the allocated memory (e.g.
```suggestion
// a compile-time guarantee that the properties of the allocated memory (for example:
```

2023-12-19 17:00 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/include/annotated_class_util.hpp
> +// buffer location, alignment) match with the annotations on the kernel arguments
```suggestion
// buffer location, alignment) match with the annotations on the kernel arguments.
```

2023-12-19 17:00 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/include/annotated_class_util.hpp
> +//    using karg_t = sycl::ext::oneapi::experimental::annotated_arg<
```suggestion
//    using annotated_arg_t = sycl::ext::oneapi::experimental::annotated_arg<
```

I don't like recommending `karg_t` because the `k` prefix is usually used to indicate a constant, and it is kind of confusing to read in code.

2023-12-19 17:00 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/include/annotated_class_util.hpp
> +// Specifically, if "-std=c++20" is supported, the type alias declaration above
```suggestion
// Furthermore, if you add the "-std=c++20" compiler flag, the type alias declaration above
```

2023-12-19 17:00 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/include/annotated_class_util.hpp
> +//    auto c = fpga_tools::alloc_annotated<karg_t>(count, q);
```suggestion
//    annotated_arg_t c = fpga_tools::alloc_annotated<annotated_arg_t>(count, q);
```

2023-12-19 17:00 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/include/annotated_class_util.hpp
> +//    using karg_t = sycl::ext::oneapi::experimental::annotated_arg<
```suggestion
//    using annotated_arg_t = sycl::ext::oneapi::experimental::annotated_arg<
```

2023-12-19 17:00 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/include/annotated_class_util.hpp
> +//    auto c = fpga_tools::alloc_annotated<karg_t>(count, q);
I don't like `auto` in example code like this because it obfuscates type information.

I can tolerate it in a code sample if and only if static analysis tools like intellisense can evaluate it:

![image](https://github.com/wangdi4/oneAPI-samples/assets/86071037/b4dbfb1b-fd1c-451c-83b2-761f2975d053)

If you need help setting up VS code intellisense, please see [this guide](https://wiki.ith.intel.com/display/HLD/VS+Code).

2023-12-19 17:00 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost/part3_hosts/src/mmhost.cpp
> +    auto array_c = fpga_tools::alloc_annotated<karg_z_t>(
```suggestion
    karg_z_t array_c = fpga_tools::alloc_annotated<karg_z_t>(
```

I don't like using `auto` because it obfuscates type info.

2023-12-19 17:00 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost/part4_ddr_hosts/src/mmhost.cpp
>      int *array_b = sycl::aligned_alloc_shared<int>(
```suggestion
    int *array_b = sycl::aligned_alloc_shared<int>(
```

Why aren't we using `alloc_annotated` for this as well? I think it's confusing to mix code styles like this.

2023-12-20 13:39 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/component_interfaces_comparison/mm-host/src/vector_add.cpp
> +    auto c = fpga_tools::alloc_annotated<karg_c_t>(count, q);
Code updated to declare the type explicitly

2023-12-20 13:40 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/component_interfaces_comparison/mm-host/src/vector_add.cpp
> +using karg_c_t = sycl::ext::oneapi::experimental::annotated_arg<
`karg_xxx` is shorthand for "kernel arguments". Type name is changed since it may cause confusion.

2023-12-20 13:49 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost/part3_hosts/src/mmhost.cpp
> +  karg_z_t z;
Yes this makes sense. I did this because I thought this could be a straightforward way for users to compare the use of `mallo_shared` and the wrapper function. But turn out it may cause confusion with use models being inconsistent among the kernel arguments.
Plus we have many other tutorials/reference designs showing the use of `malloc_shared` that can be compared with the designs using new wrapper function

2023-12-20 13:50 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost/part4_ddr_hosts/src/mmhost.cpp
>      int *array_b = sycl::aligned_alloc_shared<int>(
Updated

2023-12-20 13:50 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost/part3_hosts/src/mmhost.cpp
> +    auto array_c = fpga_tools::alloc_annotated<karg_z_t>(
Updated

2023-12-20 13:51 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/include/annotated_class_util.hpp
> +//    auto c = fpga_tools::alloc_annotated<karg_t>(count, q);
Updated to explicit type declaration

2023-12-20 13:51 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/include/annotated_class_util.hpp
> +//    using karg_t = sycl::ext::oneapi::experimental::annotated_arg<
Updated

2023-12-20 15:45 UTC, yuguen-intel commented
Hey Di,
I've discussed this change with Paul and here are the suggestions that we agreed on:
- The header should not be in the include folder, as it is experimental
- Instead of modifying existing samples, we should create a new simple sample in Tutorials/experimental to demonstrate the use of this helper function
- This helper function should be added to the sample if the intention is to be released as part of the compiler in the future

Please let us know what are your thoughts
Thanks!

2024-01-12 19:54 UTC, closed without merging