Add code sample for annotated allocation
wangdi4/oneAPI-samples pull request #13
Opened 2023-12-21 15:30 UTC by wangdi4

# Adding a New Sample(s)

## Description

Please include a description of the sample

## Checklist
Administrative
- [ ] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager

Code Development
- [ ] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [ ] Adhere to readme template 
- [ ] Enforce format via clang-format config file
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see Project Manager for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [ ] Tested using Dev Cloud when applicable

2023-12-21 15:45 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/CMakeLists.txt
> +if(UNIX)
Please use the unified cmake template from Tutorials/GettingStarted/fpga_template
The sample should also be registered in the top level FPGA README

2023-12-21 15:45 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +In the `hls_flow_interface/mmhost` sample, we demonstrated the usage of `annotated_arg` class in customizing Avalon memory-mapped interfaces for the FPGA IP component.To learn more about using `annot
```suggestion
In the `hls_flow_interface/mmhost` sample, we demonstrated the usage of `annotated_arg` class in customizing Avalon memory-mapped interfaces for the FPGA IP component. To learn more about using `annotated_arg` class to customize Avalon memory-mapped interfaces, refer to the code sample [`hls_flow_interface/mmhost`](/DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost).
```

2023-12-21 15:45 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +```c++
Can this be simplified to a single `annotated_arg`?

2023-12-21 15:45 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/sample.json
> +  "guid": "69415BED-D452-449A-8F5A-DB01ACCE38DC",
Is this a new unique guid? https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification#guid

2023-12-21 15:45 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/sample.json
> +  "name": "Invocation Interfaces",
This needs to be renamed

2023-12-21 20:32 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +```c++
updated

2023-12-21 20:32 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/sample.json
> +  "guid": "69415BED-D452-449A-8F5A-DB01ACCE38DC",
updated

2023-12-21 20:32 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/sample.json
> +  "name": "Invocation Interfaces",
fixed

2023-12-22 16:13 UTC, KevinUTAT commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +   The `fpga_emu` and `fpga_sim` targets produce binaries that you can run. The executables will be called `TARGET_NAME.fpga_emu`, `TARGET_NAME.fpga_sim`, and `TARGET_NAME.fpga`, where `TARGET_NAME`
```suggestion

   The `fpga_emu` and `fpga_sim` targets produce binaries that you can run. The executables will be called `TARGET_NAME.fpga_emu`, `TARGET_NAME.fpga_sim`, and `TARGET_NAME.fpga`, where `TARGET_NAME` is the value you specify in `CMakeLists.txt`.
```

Add an empty line so that the paragraph don't get included into the table.

2023-12-22 16:13 UTC, KevinUTAT commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +   The `fpga_emu` and `fpga_sim` targets also produce binaries that you can run. The executables will be called `TARGET_NAME.fpga_emu.exe`, `TARGET_NAME.fpga_sim.exe`, and `TARGET_NAME.fpga.exe`, whe
```suggestion

   The `fpga_emu` and `fpga_sim` targets also produce binaries that you can run. The executables will be called `TARGET_NAME.fpga_emu.exe`, `TARGET_NAME.fpga_sim.exe`, and `TARGET_NAME.fpga.exe`, where `TARGET_NAME` is the value you specify in `CMakeLists.txt`.
```

2024-01-12 19:28 UTC, tiwaria1 commented
Hey @whitepau , @yuguen-intel , this header file is meant to simplify the coding style in 2 scenarios:
1. When using oneapi::properties with any feature (eg: annotated_arg/ptr, device_globals, pipes etc)
2. When using sycl::malloc* calls for allocating USM memory.

I want to use to rename this tutorial to: "Simplifying Properties And USM Allocation coding style" (or something similar) and it will showcase 2 things:
1. simplify oneapi::properties usecase with `properties_t`
    - annotated_arg/ptr
    - device_globals
    - pipes
    - task-sequences (future)
    - axi (future)

2. simplify USM allocation code using `alloc_annotated` wrapper


Does that seem good to you both?

2024-01-12 22:14 UTC, whitepau commented
> 1. simplify oneapi::properties usecase with `properties_t`
>    
>    * annotated_arg/ptr
>    * device_globals
>    * pipes
>    * task-sequences (future)
>    * axi (future)
> 2. simplify USM allocation code using `alloc_annotated` wrapper

I like this idea. I recommend splitting this into two sub-parts then like some of the other code samples (e.g. `fpga_compile`) so that the USM/`alloc_annotated` stuff doesn't get mixed in with the `properties_t` stuff. I saw this comment after I had already written my review assuming this sample was focusing only on `alloc_annotated`, but i'll leave those comments in case we decide to keep this sample focused.

2024-01-12 22:14 UTC, whitepau requested changes

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +It is categorized as a Tier 2 sample that demonstrates a compiler feature.
I would classify this as a tier 3 sample, since it's kind of an 'advanced' 'FPGA-only' feature.

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +In the `hls_flow_interface/mmhost` sample, we demonstrated the usage of `annotated_arg` class in customizing Avalon memory-mapped interfaces for the FPGA IP component. To learn more about using `anno
```suggestion
In the `hls_flow_interfaces/mmhost` sample, we demonstrated the usage of `annotated_arg` class in customizing Avalon memory-mapped interfaces for the FPGA IP component. To learn more about using `annotated_arg` class to customize Avalon memory-mapped interfaces, refer to the code sample [hls_flow_interfaces/mmhost](/DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost).
```

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +      ```
```suggestion
   | Compilation Type    | Command
   |:---                 |:---
   | FPGA Emulator       | `make fpga_emu`
   | Optimization Report | `make report`
   | FPGA Simulator      | `make fpga_sim`
```

I have a small preference to trim this down

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +   >  ```
```suggestion
```

I have a small preference to remove this section since it's covered in a different code sample and otherwise just makes this section very long.

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +   >  ```
```suggestion
```

I prefer to keep this section short to avoid overwhelming the user.

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +      ```
```suggestion

   | Compilation Type    | Command (Windows)
   |:---                 |:---
   | FPGA Emulator       | `nmake fpga_emu`
   | Optimization Report | `nmake report`
   | FPGA Simulator      | `nmake fpga_sim`
   | FPGA Hardware       | `nmake fpga`
```
I prefer to keep the 'build' instructions short to avoid overwhelming the user

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/sample.json
> +  "guid": "7D36D250-D1B5-40B1-8B91-BB1851B0C293",
don't forget to make a unique GUID

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/sample.json
> +  "description": "An Intel® FPGA tutorial demonstrating the usage of the helper function for annotated allocation",
```suggestion
  "description": "This Intel® FPGA tutorial demonstrates how to use the alloc_annotated helper function to create annotated pointers more neatly than the standard USM allocation APIs.",
```

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +> **Note**: "annotated_alloc" function only takes `annotated_arg` with pointer type as valid template parameters.
```suggestion
> **Note**: "alloc_annotated" function only takes `annotated_arg` with pointer type as valid template parameters.
```

I won't correct these anymore; I trust you know how to use ctrl + h to find and replace :) (but be careful not to replace `annotated_allocation` :)

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +### Using `annotated_alloc` to allocate host/shared memory with properties that match with Avalon memory-mapped host interfaces
```suggestion
### Using `alloc_annotated` to allocate host/shared memory with properties that match with Avalon memory-mapped host interfaces
```

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +This tutorial demonstrates how to use the provided helper function to allocate host/shared memory with properties that match with the Avalon memory-mapped host interfaces on the IP components produce
```suggestion
This Intel® FPGA tutorial demonstrates how to use the `alloc_annotated` helper function to create annotated pointers. This function can help you write cleaner code when you use the Intel® oneAPI DDPC++/C++ Compiler to create FPGA IP modules.
```

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/src/annotated_class_util.hpp
> +// "annotated_alloc" function takes an annotated_arg type as the only template
```suggestion
// "alloc_annotated" function takes an annotated_arg type as the only template
```
please be consistent :)

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/src/annotated_class_util.hpp
> +//                  sycl::ext::oneapi::experimental::alignment<4>>;
why don't we just add the `-std=c++20` compiler flag to the CMakeLists file and then only demonstrate the simplified alias declaration?

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/src/annotated_class_util.hpp
> +// 3. in the host code, replace the "malloc_shared" call by:
```suggestion
// 3. in the host code, replace the USM allocation call with:
```
seems confusing since there are many options for USM allocations, isn't `malloc_shared` and `malloc_host` called `aligned_alloc_shared` now?

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/src/annotated_class_util.hpp
> +// pointer type as valid template parameter. Other types cause a compiler error.
```suggestion
// NOTE: The template parameter for the "alloc_annotated" function must be either an "annotated_arg" with a pointer type, or an "annotated_ptr". Other types cause a compiler error.
```

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/src/annotated_alloc.cpp
> +// resulting in three unique Avalon memory-mapped host interfaces.
```suggestion
// This type alias groups together all the properties used by the `a` pointer, and can be re-used in the annotated memory allocation in the host code.
```

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/src/annotated_alloc.cpp
> +// resulting in three unique Avalon memory-mapped host interfaces.
don't forget to fix newlines

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/src/annotated_alloc.cpp
> +    // aligned_alloc_shared API
```suggestion
    // The SYCL USM allocation API requires us to explicitly specify buffer_location and alignment when allocating the host array to ensure the allocated memory shares the same buffer location property as the corresponding kernel argument. This results in your explicitly defining these as constants in your device code (which is not very tidy) or it could result in you accidentally mis-matching these properties between your host code and device code.
```

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/src/annotated_alloc.cpp
> +    // alignment) match with the annotations on the kernel arguments.
```suggestion
    // The "alloc_annotated" function extracts the buffer location and alignment properties from the type alias annotated_arg_t, rather than forcing you to explicitly define them in your code. This
    // ensures the properties of the returned pointer match with the annotations on the kernel arguments.
```

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/src/annotated_alloc.cpp
> +    free(array_a, q);
```suggestion
    sycl::free(array_a, q);
```
i thought we were avoiding `using namespace sycl`.

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/src/annotated_alloc.cpp
> +    std::cout << "Elements in vector : " << kN << "\n";
```suggestion
    std::cout << "using aligned_alloc_shared to allocate a block of shared memory\n";
```
print something that's actually interesting to the user :)

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/src/annotated_alloc.cpp
> +    std::cout << "Elements in vector : " << kN << "\n";
```suggestion
    std::cout << "using fpga_tools::alloc_annotated to allocate a block of shared memory\n";
```

2024-01-12 22:14 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/README.md
> +Elements in vector : 8
```suggestion
```
Please change this to match the new output in annotated_alloc.cpp

2024-01-16 22:46 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/sample.json
> +  "guid": "7D36D250-D1B5-40B1-8B91-BB1851B0C293",
yes this is newly generated

2024-01-17 17:08 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_allocation/src/annotated_class_util.hpp
> +//                  sycl::ext::oneapi::experimental::alignment<4>>;
updated

2024-01-19 09:33 UTC, whitepau requested changes

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/CMakeLists.txt
> +set(COMMON_COMPILE_FLAGS -fsycl -fintelfpga -Wall -std=c++20 ${WIN_FLAG} ${DEBUG_FLAGS} ${QACTYPES} ${USER_FLAGS})
```suggestion
set(COMMON_COMPILE_FLAGS -fsycl -fintelfpga -Wall ${WIN_FLAG} ${DEBUG_FLAGS} ${QACTYPES} ${USER_FLAGS})
```
Unless you plan to update this CMake file for ALL the code samples, please don't make changes after line 49. If you want to add an extra compile flag, you can do that in line 42.

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/sample.json
> +  "description": "This Intel® FPGA tutorial demonstrates how to use the alloc_annotated helper function to create annotated pointers more neatly than the standard USM allocation APIs, and how to util
```suggestion
  "description": "An Intel® FPGA tutorial demonstrating how to use the annotated_class_util.hpp to simplify your oneAPI code"
```

be consistent with other descriptions. this is getting too long; these strings show up in the sample browser like this:

![image](https://github.com/wangdi4/oneAPI-samples/assets/86071037/631c5fa3-983d-4230-a1e5-9c8e79fbce55)

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +This Intel® FPGA tutorial demonstrates how to write cleaner code by: (i) using `properties_t` class to simplify the declaration of annotated types, and (ii) using the `alloc_annotated` helper functio
```suggestion
This Intel® FPGA tutorial demonstrates how to use the included `annotated_class_util.hpp` header file to write cleaner code. This header lets you: 
* use the `properties_t` class to simplify the declaration of annotated types
* use the `alloc_annotated` helper function to create annotated pointers more neatly than the standard USM allocation APIs.
```

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/src/annotated_class_util.hpp
>  // "annotated_alloc" function takes an annotated_arg type as the only template
```suggestion
// "alloc_annotated" function takes an annotated_arg type as the only template
```
you missed at least one... please use VS Code's search feature to look for any annotated_alloc still hanging around in your comments

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/src/annotated_coding.cpp
> +// and can be re-used in the annotated memory allocation in the host code.
```suggestion
// This type alias groups together all the properties used by the `a` pointer,
// and can be re-used in the annotated memory allocation in the host code.
// This syntax works if you have added the `-std=c++20` flag to your compiler command.
```

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/CMakeLists.txt
> +set(USER_FLAGS ${USER_FLAGS})
```suggestion
# add -std=c++20 to enable cleaner declaration of a group of properties
set(USER_FLAGS ${USER_FLAGS};-std=c++20)
```

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/src/annotated_coding.cpp
> +    // these properties between your host code and device code.
```suggestion
    // The SYCL USM allocation API requires us to explicitly specify buffer_location
    // and alignment when allocating the host array. 
    // Unless you explicitly define these as named constants in your device code
    // (which is not very tidy), you may accidentally mis-match these properties 
    // between your host code and device code.
```

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +> **Note**: to use the helper class `properties_t`, you need to add the compiler flag "-std=c++20" in your compiling command. "-std=c++20" has been added to the CMakeLists.txt file of this tutorial.
```suggestion
> **Note**: to use the helper class `properties_t`, you need to add the compiler flag "-std=c++20" to your compilation command. "-std=c++20" has been added to the `USER_FLAGS` variable in the CMakeLists.txt file of this tutorial:
> ```
> set(USER_FLAGS ${USER_FLAGS};-std=c++20)
>```
```

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +The `hls_flow_interfaces/mmhost` code sample demonstrates the usage of `annotated_arg` class in customizing Avalon memory-mapped interfaces for the FPGA IP component. (To learn more about `annotated_
```suggestion
The `annotated_arg` class can be used to customize Avalon memory-mapped interfaces for FPGA IP components. (To learn more about `annotated_arg` class, refer to the code sample [mmhost](/DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost)). This tutorial will further demonstrate how to use the helper code in `annotated_class_util.hpp` to clean up your code that uses `annotated_arg`. You may add `annotated_class_util.hpp` to your designs.
```

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +The code sample [hls_flow_interfaces/mmhost](/DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost) has demonstrated how to declare an annotated_arg type using `decltype`. For
```suggestion
Most oneAPI code assigns properties to an `annotated_arg` type using `decltype`. For example,
```

You have referred to this sample 3 times now. I've deleted all but one; we don't need to link to the same thing 3 times :)

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +The header file "annotated_class_util.hpp" provides a helper class `properties_t` (in `fpga_tools` namespace) that simplifies the code as follows
```suggestion
The header file "annotated_class_util.hpp" provides a helper class `properties_t` (in `fpga_tools` namespace) that lets you simplify your code as follows:
```

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +sycl::ext::oneapi::experimental::annotated_arg<int *, ArgProps> arg_x;
```suggestion
#include "annotated_class_util.hpp"
<...>
using ArgProps = fpga_tools::properties_t<propertiesA, 
                                                                      propertiesB, 
                                                                      propertiesC>;
sycl::ext::oneapi::experimental::annotated_arg<int *, ArgProps> arg_x;
```

please align it correctly :)

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +sycl::ext::oneapi::experimental::annotated_arg<int *, ArgProps> arg_x;
```suggestion
using ArgProps = decltype(sycl::ext::oneapi::experimental::properties{
                              propertiesA,
                              propertiesB,
                              propertiesC});
sycl::ext::oneapi::experimental::annotated_arg<int *, ArgProps> arg_x;
```

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +> **Note**: The helper class `properties_t` can be used on other annotated classes that specify properties in form of `decltype(sycl::ext::oneapi::experimental::properties{...})`, such as [device_glo
```suggestion
> **Note**: The helper class `properties_t` can be used on other annotated classes that specify properties in form of `decltype(sycl::ext::oneapi::experimental::properties{...})`, such as [device_global](/DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global) and [pipe](DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/streaming_data_interfaces), provided the header file "annotation_class_util.hpp".
```
I'd prefer you link to the pipe tutorial that demonstrates pipes for SYCL HLS components rather than the host pipes tutorial, which is pretty much useless without an appropriate BSP :)

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +When testing the functionality and performance of an IP component using FPGA simulation, it is the responsibility of the SYCL host code to provide valid runtime values that matches with the propertie
```suggestion
While SYCL device code must specify `annotated_arg` properties at **compile** time, the SYCL specification allows host code to specify these properties at **run** time. If you are designing and testing an IP component, this additional flexibility is of no use to you, so you can use the helper function `alloc_annotated()` (defined in the utility header file "annotation_class_util.hpp") to simplify your code, while still ensuring that the properties in your host allocations match the properties you defined in your device code. 
```

2024-01-19 09:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +In the example, the device code defines a SYCL kernel functor that multiplies a factor of 2 to an input vector as follows
```suggestion
In the example, the device code defines a SYCL kernel functor that multiplies a factor of 2 to an input vector as follows:
```

2024-01-19 13:58 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/src/annotated_class_util.hpp
>  // "annotated_alloc" function takes an annotated_arg type as the only template
Searched in the code sample and all the occurrences are fixed.

2024-01-19 14:22 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +sycl::ext::oneapi::experimental::annotated_arg<int *, ArgProps> arg_x;
I changed the properties to concrete properties instead of placeholders, which could be confusing.

2024-01-19 14:37 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +When testing the functionality and performance of an IP component using FPGA simulation, it is the responsibility of the SYCL host code to provide valid runtime values that matches with the propertie
updated

2024-01-22 15:08 UTC, tiwaria1 approved these changes
Requested some minor changes.

2024-01-22 15:08 UTC, tiwaria1 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +* use the `properties_t` class to simplify the declaration of annotated types
```suggestion
* use the `properties_t` alias to simplify the declaration of annotated types with groups of properties
```
Update other uses similarly

2024-01-22 15:08 UTC, tiwaria1 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +> **Note**: "alloc_annotated" function only takes `annotated_arg` over **pointer types** as the valid template parameters.
```suggestion
> **Note**: "alloc_annotated" function only takes `annotated_arg` templated with **pointer types** as the valid template parameter.
```

2024-01-22 15:08 UTC, tiwaria1 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/src/annotated_class_util.hpp
> +// parameter, and returns an instance of that annotated_arg's template type.
```suggestion
// parameter, and returns an instance of the same template type, with memory allocated for the underlying pointer.
```

2024-01-22 16:16 UTC, KevinUTAT approved these changes

2024-01-22 16:59 UTC, whitepau requested changes

2024-01-22 16:59 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +The `annotated_arg` class can be used to customize Avalon memory-mapped interfaces for FPGA IP components. (To learn more about `annotated_arg` class, refer to the code sample [mmhost](/DirectProgram
```suggestion
The `annotated_arg` class can be used to customize Avalon memory-mapped interfaces for FPGA IP components. (To learn more about the `annotated_arg` class, refer to the code sample [mmhost](/DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost)). This tutorial will further demonstrate how to use the helper code in `annotated_class_util.hpp` to clean up your code that uses `annotated_arg`. You may add `annotated_class_util.hpp` to your designs.
```

2024-01-22 16:59 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +> **Note**: to use the helper class `properties_t`, you need to add the compiler flag "-std=c++20" to your compilation command. "-std=c++20" has been added to the `USER_FLAGS` variable in the CMakeLi
```suggestion
> **Note**: to use the helper class `properties_t`, you need to add the compiler flag `-std=c++20` to your compilation command. `-std=c++20` has been added to the `USER_FLAGS` variable in the CMakeLists.txt file of this tutorial:
```

2024-01-22 16:59 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +> **Note**: The helper class `properties_t` can be used on other annotated classes that specify properties in form of `decltype(sycl::ext::oneapi::experimental::properties{...})`, such as [device_glo
```suggestion
> **Note**: The `properties_t` alias can be used on other annotated classes that specify properties in form of `decltype(sycl::ext::oneapi::experimental::properties{...})`, such as [device_global](/DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global) and [pipe](/DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/streaming_data_interfaces), assuming you have included the header file "annotation_class_util.hpp" that appears in this code sample.
```

2024-01-22 16:59 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/README.md
> +| [annotated_class_clean_coding](Tutorials/Features/experimental/annotated_class_clean_coding)  | [Tutorials/Features](Tutorials/Features)             | How to simplify the coding of annotated_arg cl
```suggestion
| [annotated_class_clean_coding](Tutorials/Features/experimental/annotated_class_clean_coding)  | [Tutorials/Features](Tutorials/Features)             | An Intel® FPGA tutorial demonstrating how to use `annotated_class_util.hpp` to simplify your oneAPI code that annotates properties to `pipe`s and `annotated_arg`

```
just be the same as sample.json :)

2024-01-22 16:59 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/sample.json
> +  "description": "An Intel® FPGA tutorial demonstrating how to use the annotated_class_util.hpp to simplify your oneAPI code",
```suggestion
  "description": " An Intel® FPGA tutorial demonstrating how to use annotated_class_util.hpp to simplify your oneAPI code that annotates properties to pipes and annotated_arg",
```

2024-01-23 09:11 UTC, whitepau approved these changes

2024-01-23 19:29 UTC, erickoeck commented on DirectProgramming/C++SYCL_FPGA/README.md
> +| [annotated_class_clean_coding](Tutorials/Features/experimental/annotated_class_clean_coding)  | [Tutorials/Features](Tutorials/Features)             | An Intel® FPGA tutorial demonstrating how to u
demonstrating -> that demonstrates

2024-01-23 19:29 UTC, erickoeck commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +* use the `properties_t` alias to simplify the declaration of annotated types with groups of properties
Rewrite to emphasize the benefit and not the use:

Simply the declaration of...by using the `properties_t` alias.

2024-01-23 19:29 UTC, erickoeck commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +* use the `alloc_annotated` helper function to create annotated pointers more neatly than the standard USM allocation APIs.
Create annotated pointers more neatly....by using the `alloc_annotated` helper function.

2024-01-23 19:29 UTC, erickoeck commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +This Intel® FPGA tutorial demonstrates how to use the included `annotated_class_util.hpp` header file to write cleaner code. This header lets you:
Introduce lists with a full sentence. For example, you could say, "You can use this header file to write cleaner code as follows:"

2024-01-23 19:29 UTC, erickoeck commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +> **Note**: This tutorial will not work for a Full System compile as it demonstrates a SYCL HLS flow specific feature.
"Full System" is now "FPGA acceleration".

This tutorial does not apply to the FPGA acceleration flow. It demonstrates features specific to the SYCL HLS flow.

2024-01-23 19:29 UTC, erickoeck commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +### Use `properties_t` to simplify the declaration of annotated types with groups of properties
Simply the declaration....

Also, headings should use headline-style capitalization:

Simplify the Declaration of Annotated Types By Using The `properties_t` Alias? Template Class? with Groups of Properties

2024-01-23 19:29 UTC, erickoeck commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +### Use helper function `alloc_annotated` to allocate host/shared memory with properties that match with Avalon memory-mapped host interfaces
Allocate Host/Shared Memory....

2024-01-23 19:29 UTC, erickoeck commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +The type of the kernel argument `a` is annotated_arg specified with properties `buffer location` and `alignment`. To test the IP component in the FPGA simulation, the SYCL host code is required to pr
annotated_arg -> `annotated_arg`

2024-01-23 20:44 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/README.md
> +| [annotated_class_clean_coding](Tutorials/Features/experimental/annotated_class_clean_coding)  | [Tutorials/Features](Tutorials/Features)             | An Intel® FPGA tutorial demonstrating how to u
Removed "An Intel® FPGA tutorial demonstrating" to keep it consistent with other code sample entries

2024-01-23 21:00 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +The type of the kernel argument `a` is annotated_arg specified with properties `buffer location` and `alignment`. To test the IP component in the FPGA simulation, the SYCL host code is required to pr
updated

2024-01-23 21:00 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +### Use helper function `alloc_annotated` to allocate host/shared memory with properties that match with Avalon memory-mapped host interfaces
Updated.

2024-01-23 21:00 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +### Use `properties_t` to simplify the declaration of annotated types with groups of properties
Updated.

2024-01-23 21:00 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +> **Note**: This tutorial will not work for a Full System compile as it demonstrates a SYCL HLS flow specific feature.
Updated.

2024-01-23 21:00 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +This Intel® FPGA tutorial demonstrates how to use the included `annotated_class_util.hpp` header file to write cleaner code. This header lets you:
Updated.

2024-01-23 21:00 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +* use the `alloc_annotated` helper function to create annotated pointers more neatly than the standard USM allocation APIs.
Updated.

2024-01-23 21:00 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/README.md
> +* use the `properties_t` alias to simplify the declaration of annotated types with groups of properties
Updated.

2024-01-25 14:46 UTC, closed without merging