Annotated ptr
wangdi4/oneAPI-samples pull request #14
Opened 2024-01-11 19:37 UTC by wangdi4

# Adding a New Sample(s)

## Description

Add `annotated_ptr` code sample

## Checklist
Administrative
- [ ] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager

Code Development
- [ ] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [ ] Adhere to readme template 
- [ ] Enforce format via clang-format config file
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see Project Manager for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [ ] Tested using Dev Cloud when applicable

2024-01-15 17:14 UTC, ajaykumarkannan reviewed
I caught a number of typos but can you run this README through a spell checker as well?

2024-01-15 17:14 UTC, ajaykumarkannan commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +In the `hls_flow_interface/mmhost` sample(/DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost), we demonstrated the usage of `annotated_arg` class in customizing Avalon memo
```suggestion
The `hls_flow_interfaces/mmhost` sample (/DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost) demonstrates the usage of `annotated_arg` class in customizing Avalon memory-mapped interfaces for the FPGA IP component. 
Sometimes annotations need to be applied on pointers inside the kernel to enable certain compiler optimizations. 
This tutorial shows how to use `annotated_ptr` to annotate a specific buffer location  to a pointer, which reduces the LSUs use in the produced FPGA IP component.
```

2024-01-15 17:14 UTC, ajaykumarkannan commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +The address of the weight matrix, however, is transferred into the kernel via a host pipe. The kernel reads the row pointers of the weight matrix:
```suggestion
The address of the weight matrix is transferred into the kernel via a host pipe. The kernel reads the row pointers of the weight matrix:
```

2024-01-15 17:14 UTC, ajaykumarkannan commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +Since the pointer `p` is read from a pipe, the buffer lcoation of the pointer is ambiguous. The compiler will build two sets of LSUs that connect to buffer locatoin 1 and buffer location 2 separately
```suggestion
Since the pointer `p` is read from a pipe, the buffer location of the pointer is ambiguous. The compiler will build two sets of LSUs that connect to buffer location 1 and buffer location 2 separately, which increases the kernel area.
```

2024-01-15 17:14 UTC, ajaykumarkannan commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +As a result, the compiler will build only one set of LSUs that connect to buffer locatoin 1.
```suggestion
As a result, the compiler will build only one set of LSUs that connect to buffer location 1.
```

2024-01-15 17:14 UTC, ajaykumarkannan commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +## Building the `anntotated_ptr` Tutorial
```suggestion
## Building the `annotated_ptr` Tutorial
```

2024-01-16 13:29 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +This tutorial demonstrates how to use `annotated_ptr` to annotate properties to pointers inside the kernel, which enables certain compiler optimization that reduces the area usage of the FPGA IP comp
run-on sentence

2024-01-16 14:22 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +In the example, the device code defines a SYCL kernel functor that computes the dot product between a weight matrix (located in buffer location 1) and a vector (located in buffer location 2), and sav
this is a somewhat complicated design with 2 dedicated buffer locations (possibly 3- see my comment in annotated_ptr.cpp) and a streaming interface. Can you please make a diagram? I shared a link to you of a visio drawing that has some nice primitives that you can use.

2024-01-16 14:22 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +Since the pointer `p` is read from a pipe, the buffer lcoation of the pointer is ambiguous. The compiler will build two sets of LSUs that connect to buffer locatoin 1 and buffer location 2 separately
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

this extension is enormously helpful 😊

2024-01-16 14:22 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +Since the pointer `p` is read from a pipe, the buffer lcoation of the pointer is ambiguous. The compiler will build two sets of LSUs that connect to buffer locatoin 1 and buffer location 2 separately
"Since the pointer `p` is read from a pipe, the buffer location of the pointer is ambiguous."

I've seen ambiguous pointers in other designs too. How can the user see that a pointer has an ambiguous buffer location? Include a screenshot of the appropriate reports to show this (I think the system viewer is probably where to start)

2024-01-16 14:22 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +   result[i] += data[j] * mul[j];
I thought `annotated_ptr` didn't support the `[]` operator? Or is that just when the `annotated_ptr` has a `align` property set? Or perhaps I'm just not remembering that limitation correctly.

2024-01-16 14:22 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +
```suggestion
```
I have a small preference to remove this section since it's covered in a different code sample and otherwise just makes this section very long.

2024-01-16 14:22 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +   ```
```suggestion
	   | Compilation Type    | Command
	   |:---                 |:---
	   | FPGA Emulator       | `make fpga_emu`
	   | Optimization Report | `make report`
	   | FPGA Simulator      | `make fpga_sim`
```
I have a small preference to trim this down. Refer to fpga_template if you want to emphasize these details.

2024-01-16 14:22 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +   >  ```
```suggestion
```

I prefer to keep this section short to avoid overwhelming the user. link to fpga_template if you really want to show this stuff

2024-01-16 14:22 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +   ```
```suggestion
	   | Compilation Type    | Command (Windows)
	   |:---                 |:---
	   | FPGA Emulator       | `nmake fpga_emu`
	   | Optimization Report | `nmake report`
	   | FPGA Simulator      | `nmake fpga_sim`
	   | FPGA Hardware       | `nmake fpga`
```
I prefer to keep the 'build' instructions short to avoid overwhelming the user.

2024-01-16 14:22 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +Navigate to *System Viewer* (*Views* > *System Viewer*) and click on *Global memory* in the *System* hierarchy. Observe that the compiler generates a number of `COLS` LD nodes connected to global mem
a screenshot would be nice.

2024-01-16 14:22 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/sample.json
> +  "guid": "A40887C1-25D3-41EA-9695-1260ADE5EAAA",
make sure this is a new GUID

2024-01-16 19:58 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +   result[i] += data[j] * mul[j];
`annotated_ptr` doesn't support [] operator only when alignment is specified. For 2024.1 we only document using `annotated_ptr` to specify buffer locations inside a kernel

2024-01-16 20:33 UTC, whitepau requested changes

2024-01-16 20:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/sample.json
> +  "guid": "A40887C1-25D3-41EA-9695-1260ADE5EAAA",
make sure this is a new GUID

2024-01-16 20:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/sample.json
> +  "categories": ["Toolkit/oneAPI Direct Programming/C++SYCL FPGA/Getting Started Tutorials"],
```suggestion
  "categories": ["Toolkit/oneAPI Direct Programming/C++SYCL FPGA/Tutorials/Features/experimental"],
```

2024-01-16 20:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/sample.json
> +  "description": "An Intel® FPGA tutorial demonstrating using annotated_ptr to annotate pointers inside kernel",
```suggestion
  "description": "An Intel® FPGA tutorial demonstrating how to use annotated_ptr to customize a memory-mapped or global memory interface",
```

2024-01-16 20:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/sample.json
> +    "base": "../../..",
```suggestion
    "base": "../../../..",
```

2024-01-16 20:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/sample.json
> +          "cd ../../..",
```suggestion
          "cd ../../../..",
```

2024-01-16 20:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/sample.json
> +          "cd ../../..",
```suggestion
          "cd ../../../..",
```

2024-01-16 20:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/src/annotated_ptr.cpp
> +using namespace ext::oneapi::experimental;
```suggestion
```
fully elaborate namespaces.

I will once again express my displeasure that bufferlocation lives in `sycl::ext::oneapi::experimental` as that's a lovely trap to set for people.

2024-01-16 20:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/src/annotated_ptr.cpp
> +      annotated_ptr<float, decltype(properties{buffer_location<kBL1>})> data{p};
there should be an additional kernel that shows what happens when you don't specify `annotated_ptr` so the user sees what an ambiguous buffer location looks like in the report

2024-01-16 20:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/src/annotated_ptr.cpp
> +      annotated_ptr<float, decltype(properties{buffer_location<kBL1>})> data{p};
```suggestion
      annotated_ptr<float, decltype(properties{buffer_location<kBL3>})> data{p};
```
Would it make sense to put `data` in a 3rd buffer location so that it's clear that the global memory accesses won't arbitrate? that will be a simpler data model (although the IP will have 3 mm host interfaces)

2024-01-16 20:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/README.md
> +| [annotated_ptr (experimental)](Tutorials/Features/experimental/annotated_ptr) | [Tutorials/Features](Tutorials/Features)             | How to annotate a pointer inside the kernel using `annotated_p
```suggestion
| [annotated_ptr (experimental)](Tutorials/Features/experimental/annotated_ptr) | [Tutorials/Features](Tutorials/Features)             | How to use `annotated_ptr` to constrain a specific memory access

```

2024-01-16 20:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +This tutorial demonstrates how to use `annotated_ptr` to annotate properties to pointers inside the kernel, which enables certain compiler optimization that reduces the area usage of the FPGA IP comp
```suggestion
This tutorial demonstrates how to use `annotated_ptr` to constrain memory accesses in your kernel code. This can help you build more efficient FPGA IP components with the Intel® oneAPI DPC++/C++ Compiler.
```

2024-01-16 20:33 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/src/annotated_ptr.cpp
> +    // create testData
```suggestion
    // create testData. The pointers in this array will be written to our kernel through a pipe.
```

2024-01-17 18:49 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +In the example, the device code defines a SYCL kernel functor that computes the dot product between a weight matrix (located in buffer location 1) and a vector (located in buffer location 2), and sav
diagram added

2024-01-17 19:36 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/sample.json
> +  "guid": "A40887C1-25D3-41EA-9695-1260ADE5EAAA",
yes this is new GUID

2024-01-17 19:39 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/sample.json
> +  "description": "An Intel® FPGA tutorial demonstrating using annotated_ptr to annotate pointers inside kernel",
The use of annotated_ptr on kernel arguments for mmhost customization will not be documented in 2024.1

2024-01-17 20:44 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/src/annotated_ptr.cpp
> +      annotated_ptr<float, decltype(properties{buffer_location<kBL1>})> data{p};
No the buffer location of the pointers read from pipe has to be one `kBL1` of `kBL2`, because the kernel mmhost interfaces are determined by the annotations on the kernel arguments.  So specifying a local variable to `kBL3` will result in an error like "can't find global memory kBL3 in board spec"

2024-01-18 13:12 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +Since the pointer `p` is read from a pipe, the buffer lcoation of the pointer is ambiguous. The compiler will build two sets of LSUs that connect to buffer locatoin 1 and buffer location 2 separately
I've changed the wording from "ambiguous" to "not inferable" to be more straightforward.

2024-01-18 13:13 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/src/annotated_ptr.cpp
> +      annotated_ptr<float, decltype(properties{buffer_location<kBL1>})> data{p};
Updated

2024-01-18 22:51 UTC, ajaykumarkannan approved these changes

2024-01-19 10:03 UTC, whitepau requested changes

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/CMakeLists.txt
> +target_include_directories(${EMULATOR_TARGET} PRIVATE ../../../../include)
```suggestion
```
If you are changing the CMake file from fpga_template, please only make changes above line 43.

the variable USER_INCLUDE_PATHS lets you control this include path!!!

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/CMakeLists.txt
> +    set(FMA_FLAG "/Qfma-")
```suggestion
```
Why did you add fp-model=precise? If you are changing the CMake file from fpga_template, please only make changes above line 43.

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/CMakeLists.txt
> +    set(FMA_FLAG "-no-fma")
```suggestion
```
Why did you add fp-model=precise? If you are changing the CMake file from fpga_template, please only make changes above line 43.

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/CMakeLists.txt
> +set(COMMON_COMPILE_FLAGS -fsycl -fintelfpga -Wall ${WIN_FLAG} ${DEBUG_FLAGS} ${QACTYPES} ${FMA_FLAG} ${FP_MODEL} ${USER_FLAGS})
```suggestion
set(COMMON_COMPILE_FLAGS -fsycl -fintelfpga -Wall ${WIN_FLAG} ${DEBUG_FLAGS} ${QACTYPES} ${USER_FLAGS})
```
If you are changing the CMake file from fpga_template, please only make changes above line 43.

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/CMakeLists.txt
> +target_include_directories(${EMULATOR_TARGET} PRIVATE ../../../../include)
```suggestion
```
If you are changing the CMake file from fpga_template, please only make changes above line 43.

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/CMakeLists.txt
> +target_include_directories(${EMULATOR_TARGET} PRIVATE ../../../../include)
```suggestion
```
If you are changing the CMake file from fpga_template, please only make changes above line 43.

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/CMakeLists.txt
> +target_include_directories(${EMULATOR_TARGET} PRIVATE ../../../../include)
```suggestion
```
If you are changing the CMake file from fpga_template, please only make changes above line 43.

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +   style tier4 fill:#0071c1,stroke:#0071c1,stroke-width:1px,color:#fff
```suggestion
   style tier1 fill:#0071c1,stroke:#0071c1,stroke-width:1px,color:#fff
   style tier2 fill:#0071c1,stroke:#0071c1,stroke-width:1px,color:#fff
   style tier3 fill:#f96,stroke:#333,stroke-width:1px,color:#fff
   style tier4 fill:#0071c1,stroke:#0071c1,stroke-width:1px,color:#fff
```

if it's tier 3 then highlight the tier 3 bubble

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +It is categorized as a Tier 3 sample that demonstrates a design pattern.
```suggestion
It is categorized as a Tier 3 sample that demonstrates an advanced code optimization.
```

not a design pattern

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +The [`hls_flow_interfaces/mmhost`] (/DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost) code sample demonstrates the usage of `annotated_arg` class in customizing Avalon me
```suggestion
The [hls_flow_interfaces/mmhost](/DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost) code sample demonstrates how to use the `annotated_arg` wrapper class to customize an Avalon memory-mapped interface for an FPGA IP component.
```
hyperlink doesn't work when you write it this way

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/src/annotated_ptr.cpp
> +      annotated_ptr<float, decltype(properties{buffer_location<kBL1>})> data{p};
what if you add an extra kernel argument?

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/sample.json
> +  "description": "An Intel® FPGA tutorial demonstrating using annotated_ptr to annotate pointers inside kernel",
then say 'constrain' instead of 'annotate'. we can't just say 'use annotated_ptr to annotate a pointer'; that's self-evident from the name 'annotated_ptr' :) and begs the question "what does 'annotate' mean?".

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +   result[i] += data[j] * mul[j];
This memory access is in an unrolled loop, so the optimal behaviour is to specify the `align` property and get coalesced LSUs. That conveniently also doesn't hide this nasty usability restriction.

You don't need to write about the `[]` not being supported in the Readme, but please make a comment in the source to indicate why you're de-referencing the aligned `annotated_ptr` before accessing it.

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +In the example, the device code defines a SYCL kernel functor that computes the dot product between a weight matrix (located in buffer location 1) and a vector (located in buffer location 2), and sav
```suggestion
In the example, the device code defines a SYCL kernel functor that computes the dot product between a weight matrix (located in buffer location 1) and a vector (located in buffer location 2), and saves to the result vector (located in buffer location 1).
```

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +On the other hand, the address to each row of the weight matrix is transferred into the kernel via a host pipe. The kernel reads the row pointers of the weight matrix and then perform the dot product
```suggestion
The address to each row of the weight matrix is transferred into the kernel via a host pipe. The kernel reads the row pointers of the weight matrix and then performs the dot product operation.
```
'on the other hand' usually is used when you are comparing relative costs and benefits of two alternatives. In this case, you are describing two parts of the same IP, so 'on the other hand' feels kind of awkward here.

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +Sometimes annotations need to be applied on pointers inside the kernel to enable certain compiler optimizations. This tutorial shows how to use `annotated_ptr` to constrain memory accesses to a point
```suggestion
Sometimes annotations need to be applied on pointers inside the kernel to enable certain compiler optimizations. This tutorial shows how to use `annotated_ptr` to constrain memory accesses to a pointer variable inside the kernel, which reduces the number of Load/Store Units (LSUs) used in the generated FPGA IP component.
```

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +### An FPGA component that contains memory access to unknown buffer location
```suggestion
### An FPGA component that contains memory access to an ambiguous buffer location
```

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +- `p[j]`: buffer location is not inferrable. So the compiler will generate `COLS` Load units connected to buffer location 1 and `COLS` Load units connected to buffer location 2, because of the loop u
```suggestion
- `p[j]`: buffer location is ambiguous because `p` is simply a `float *` without any annotations telling the compiler which buffer locations it should be assigned to. So the compiler will generate load units connected to buffer location 1 **and** load units connected to buffer location 2. This is illustrated in the FPGA report, see [Read the Reports] below for more details.
```
the loop unroll is irrelevant to the buffer location being ambiguous.
I don't know how to link to sections within a markdown doc, but please link to Read the Reports :)

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +- `in_vec[j]`: located in buffer location 2. The compiler will generate `COLS` Load units because of the loop unroll.
```suggestion
- `in_vec[j]`: The compiler knows this accesses buffer location 2 because `in_vec` is an annotated kernel argument.
```

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +- `out_vec[j]`: located in buffer location 1. The compiler will generate 1 Store unit.
```suggestion
- `out_vec[j]`: The compiler knows this accesses buffer location 1 because `out_vec` is an annotated kernel argument.
```

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +You can provide the buffer location information of `p` to the compiler by using `annotated_ptr`, and then use the annotated_ptr local variable in the dot-product computation
```suggestion
You can provide the buffer location information of `p` to the compiler by wrapping it in an `annotated_ptr`, and then use the `annotated_ptr` local variable in the dot-product computation
```

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +Now all the global memory access are specified to a buffer location including `p`, which is located in buffer location 1. This will eliminate the `COLS` Load units connected to buffer location 2, red
```suggestion
Now all the global memory accesses are assigned to a specific buffer location, including `p`, which is located in buffer location 1. This removes half of the load units connected to buffer location 2, saving significant FPGA resources.
```
I think it's half of the LSUs connected to BL2? can you please check?

2024-01-19 10:03 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/src/annotated_ptr.cpp
> +  annotated_arg<float *, decltype(properties{buffer_location<kBL1>})> out_vec;
please set the alignment property so that this makes a more efficent memory system.

2024-01-22 04:53 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +Now all the global memory access are specified to a buffer location including `p`, which is located in buffer location 1. This will eliminate the `COLS` Load units connected to buffer location 2, red
yes, it reduced the LSUs to BL2 by half

2024-01-22 05:03 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/CMakeLists.txt
> +    set(FMA_FLAG "-no-fma")
`fp-model=precise` is added because the design checks the computed results of the kernel by comparing it with the same function computed in host.

Has remove this change and moved the flag into `USER_FPGA_FLAGS`

2024-01-22 05:04 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/CMakeLists.txt
> +    set(FMA_FLAG "/Qfma-")
`fp-model=precise` is added because the design checks the computed results of the kernel by comparing it with the same function computed in host.

Has remove this change and moved the flag into `USER_FPGA_FLAGS`

2024-01-22 05:24 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/src/annotated_ptr.cpp
> +      annotated_ptr<float, decltype(properties{buffer_location<kBL1>})> data{p};
This design (dot product between matrix and vector) mainly consists of 3 parts of data:
- input vector (kBL2, passed by kernel argument)
- output vector (kB1,  passed by kernel argument)
- matrix (kB1,  passed by host pipe and annotated inside the kernel)

The two kernel arguments are necessary in generating the two mmhosts, and the matrix annotated using `annotated_ptr` is the gist of this code sample. An extra kernel argument seems not necessary regarding the current functionality of the design.

2024-01-22 06:19 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/src/annotated_ptr.cpp
> +  annotated_arg<float *, decltype(properties{buffer_location<kBL1>})> out_vec;
Right now using annotated_ptr with `alignment` does not lead the compiler to generate aligned LSUs, as operator `[]` is disabled when alignment is present.  Then `get()` must be called and annotation is dropped.  

And mmhost macros also don't work.

In fact, the purpose of unrolling the loop is to make the area reduction more significant.

2024-01-22 06:20 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +   result[i] += data[j] * mul[j];
Please see the comment in the bottom

2024-01-22 16:32 UTC, whitepau requested changes

2024-01-22 16:32 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +Sometimes annotations need to be applied on pointers inside the kernel to enable certain compiler optimizations. This tutorial shows how to use `annotated_ptr` to constrain memory accesses to a point
```suggestion
A useful design optimization in FPGA SYCL code is to design with multiple buffer locations, (either multiple memory channels in a full SYCL system, or multiple memory-mapped host interfaces in a SYCL HLS IP). If your code contains un-annotated pointers, the compiler will not know at compile time which buffer location to assign to load/store units (LSUs) associated with that pointer. This tutorial shows how to use `annotated_ptr` to constrain memory accesses to a pointer variable inside the kernel, which reduces the number of LSUs used in the generated FPGA IP component.
```
I'd like this to be more specific. "**sometimes** annotations need to be applied... **certain** compiler optimizations..." is very vague language that is not actionable for someone. They should understand from this paragraph whether this code sample applies for them, and this sentence doesn't tell them that :)

2024-01-22 16:32 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +- `p[j]`: buffer location is ambiguous because `p` is simply a `float *` without any annotations telling the compiler which buffer locations it should be assigned to. So the compiler will generate lo
```suggestion
- `p[j]`: buffer location is ambiguous because `p` is simply a `float *` without any annotations telling the compiler which buffer location it should be assigned to. So the compiler will generate load units connected to buffer location 1 **and** load units connected to buffer location 2. This is illustrated in the FPGA report, see [Read the Reports](#read-the-reports) below for more details.
```

2024-01-22 16:32 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +Now all the global memory accesses are assigned to a specific buffer location, including `p`, which is located in buffer location 1. This removes half of the Load units connected to buffer location 2
```suggestion
Now all the global memory accesses are assigned to a specific buffer location, including `p`, which is located in buffer location 1. This removes half of the load units connected to buffer location 2, saving significant FPGA resources.
```

'Load' does not need to be capitalized (unless it's the first word of a sentence 😊)

2024-01-22 16:32 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/src/annotated_ptr.cpp
>  using namespace sycl::ext::oneapi::experimental;
```suggestion
```
I thought i asked for this to be removed already, but I may have asked for this to be removed in your other code sample and forgotten to add it here.

2024-01-22 16:32 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +
This is a good place to mention the limitaitons of `annotated_ptr` that we've discussed already.

1. The `buffer_location` that is passed to `annotated_ptr` must be one of the buffer locations already assigned to global memory kernel arguments (so `buffer_location<3>` would not work).
2. You cannot use the `alignment` property with an `annotated_ptr` (mention what the consequence will be).

2024-01-22 20:20 UTC, tiwaria1 approved these changes
Great work Di!

2024-01-23 09:35 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/src/annotated_ptr.cpp
>  using namespace sycl::ext::oneapi::experimental;
Fixed

2024-01-23 09:36 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +Sometimes annotations need to be applied on pointers inside the kernel to enable certain compiler optimizations. This tutorial shows how to use `annotated_ptr` to constrain memory accesses to a point
Update.  Do we need to mention the case in full-system "either multiple memory channels in a full SYCL system"?

2024-01-23 10:32 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +
Limitation is added

2024-01-23 11:17 UTC, whitepau requested changes
Nice code sample. Please make the requested minor readme enhancements, then you can put this on the code samples repo.

2024-01-23 11:17 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +A useful design optimization in FPGA SYCL code is to design with multiple buffer locations, (either multiple memory channels in a full SYCL system, or multiple memory-mapped host interfaces in a SYCL
```suggestion
A useful design optimization in FPGA SYCL code is to design with multiple buffer locations, (either multiple memory channels in a full SYCL system, or multiple memory-mapped host interfaces in a SYCL HLS IP). If your code contains un-annotated pointers (e.g. float *), the compiler will not know at compile time which buffer location to assign to load/store units (LSUs) associated with that pointer. This tutorial shows how to use `annotated_ptr` to constrain memory accesses to a pointer variable inside the kernel, which reduces the number of LSUs used in the generated FPGA IP component.
```
sorry i should have included this example since 'unannotated pointer' is very much a weird SYCL thing and not something your average C++ user would understand.

2024-01-23 11:17 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +> **Note**: The buffer_location that is passed to `annotated_ptr` must be one of the buffer locations already assigned to global memory kernel arguments (in this case, buffer location `kBL1` and `kBL
```suggestion
> [!WARNING]
> The buffer location that is passed to `annotated_ptr` must be one of the buffer locations already assigned to global memory kernel arguments (in this case, buffer location `kBL1` and `kBL2`).
```

I want to draw more attention to these as they are major gotchas. apparently this syntax works in github:

https://github.com/orgs/community/discussions/16925

2024-01-23 11:17 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/src/annotated_ptr.cpp
> +        sycl::ext::intel::experimental::property::usm::buffer_location(kBL1));
I... just realized that buffer location that you pass to `malloc_shared` is a different type than the buffer location you pass to `annotated_arg`. that's pretty confusing. a good justification for your other code sample :)

2024-01-23 11:17 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +> **Note**: Right now the `alignment` property is not supported by the `annotated_ptr` class. Therefore, the consecutive memory accesses via the pointer `mat` in the unrolled loop will not result in
```suggestion

> [!WARNING]
> The `annotated_ptr` class does not currently support the `alignment` property. Therefore, the consecutive memory accesses via the pointer `mat` in the unrolled loop cannot be configured to generate a statically coalesced load unit.
```
add a newline so these don't merge together in the same note

2024-01-23 19:37 UTC, erickoeck commented on DirectProgramming/C++SYCL_FPGA/README.md
> +| [annotated_ptr (experimental)](Tutorials/Features/experimental/annotated_ptr) | [Tutorials/Features](Tutorials/Features)             | How to use `annotated_ptr` to constrain a specific memory acce
How to use **the** `annotated_ptr` ***thing*** *alias? template?* ...

2024-01-23 19:37 UTC, erickoeck commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +This tutorial demonstrates how to use `annotated_ptr` to constrain memory accesses in your kernel code. This can help you build more efficient FPGA IP components with the Intel® oneAPI DPC++/C++ Comp
how to use **the** `annotate_ptr` ***what?*** to constrain...

2024-01-23 19:37 UTC, erickoeck commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +### An FPGA component that contains memory access to an ambiguous buffer location
Use headline case "An FPGA **C**omponent **T**hat **C**ontains..."

2024-01-23 19:59 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/README.md
> +| [annotated_ptr (experimental)](Tutorials/Features/experimental/annotated_ptr) | [Tutorials/Features](Tutorials/Features)             | How to use `annotated_ptr` to constrain a specific memory acce
Updated to "... use the `annotated_ptr` class to ..."

2024-01-23 19:59 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +This tutorial demonstrates how to use `annotated_ptr` to constrain memory accesses in your kernel code. This can help you build more efficient FPGA IP components with the Intel® oneAPI DPC++/C++ Comp
same as above

2024-01-23 19:59 UTC, wangdi4 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_ptr/README.md
> +### An FPGA component that contains memory access to an ambiguous buffer location
Fixed

2024-01-25 14:46 UTC, closed without merging